# Generated by Django 3.2 on 2021-08-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'verbose_name_plural': 'Prerequisites'},
        ),
        migrations.AlterField(
            model_name='class',
            name='enrollment_limit',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='board_type',
            field=models.CharField(choices=[('Wall-mounted', 'Wall-mounted'), ('Mobile whiteboard', 'Mobile whiteboard'), ('Glassboard', 'Glassboard'), ('Glassboard', 'Chalkboard')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Windows PC', 'Windows PC'), ('Linux PC', 'Linux PC'), ('Tablet', 'Tablet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('Network', 'Network'), ('Web design', 'Web design'), ('Software development', 'Software development')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('Projector', 'Projector'), ('Microphone', 'Microphone'), ('Online media stream', 'Online media stream'), ('Tv', 'Tv'), ('Printer', 'Printer')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prerequisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc_data.prerequisites'),
        ),
    ]
