# Generated by Django 3.2 on 2021-08-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_data', '0002_auto_20210802_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(max_length=1000),
        ),
    ]
