# Generated by Django 3.2 on 2021-08-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc_data', '0003_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sc_data.teacher'),
        ),
    ]
