# Generated by Django 3.2 on 2021-08-02 17:52

from django.db import migrations, models
import sc_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_data', '0004_alter_media_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=sc_data.models.Classroom, on_delete=sc_data.models.Classroom, to='sc_data.lab'),
        ),
    ]
